#!/bin/sh -e
#
# ==============================================================================
# PAQUETE: canaima-estilo-visual-gnome
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2010-2012 Luis Alejandro Martínez Faneyth <luis@huntingbears.com.ve>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

ERROR() {
	printf "\033[1,31m${1}\033[0m\n"
}

ADVERTENCIA() {
	printf "\033[1,33m${1}\033[0m\n"
}

EXITO() {
	printf "\033[1,32m${1}\033[0m\n"
}

case ${1} in
	configure|'')

	if [ -n "$( which glib-compile-schemas )" ] && [ -x "$( which glib-compile-schemas )" ]; then
		sync
		glib-compile-schemas /usr/share/glib-2.0/schemas || true
	fi

	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		ERROR "postinst no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
